openapi: 3.0.0
info:
  title: Emoji API
  description: Send emojis to your favorite streamer
  version: 1.0.0

x-amazon-apigateway-cors:
  allowOrigins:
    - '*'
  allowMethods:
    - POST
  allowHeaders:
    - content-type
  maxAge: 3600

paths:
  /{topic}:
    parameters:
      - in: path
        name: topic
        required: true
        schema:
          type: string
    get:
      summary: Returns an HTML page with the emojis you can react with
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
        500:
          $ref: '#/components/responses/InternalServerError'



components:
  responses:
    InternalServerError: #500
      description: The server encountered an unexpected condition which prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: An error occurred saving the item.
            required:
              - message
