AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backing service for emoji Chrome extension

Parameters:
  MomentoApiKey:
    Type: String
    NoEcho: true
  HostedZoneId:
    Type: String

Metadata:
  esbuild-properties: &esbuild-properties
    Format: esm
    Minify: true
    OutExtension:
      - .js=.mjs
    Target: es2020
    Sourcemap: false
    EntryPoints:
      - index.mjs
    Banner:
      - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
    External:
      - '@aws-sdk/*'

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 15
    MemorySize: 1024
    CodeUri: functions
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  EmojiApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: v1
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  GetReactionsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - get-reactions.mjs
    Properties:
      Handler: get-reactions.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          MOMENTO_API_KEY: !Ref MomentoApiKey
          CACHE_NAME: bis
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref EmojiApi
            Path: /{topic}
            Method: GET

  ForwardMomentoDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: False
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: momentoOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: True
        PriceClass: PriceClass_100
        Origins:
          - Id: momentoOrigin
            DomainName: api.cache.cell-us-east-1-1.prod.a.momentohq.com
            OriginPath: /topics/bis
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: Authorization
                HeaderValue: !Ref MomentoApiKey
        ViewerCertificate:
          AcmCertificateArn: !Ref SubdomainCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - momento.helton.farm

  SubdomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: momento.helton.farm
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: momento.helton.farm
          HostedZoneId: !Ref HostedZoneId

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: momento.helton.farm
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt ForwardMomentoDistribution.DomainName

  MomentoCacheDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: False
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: momento
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Ref TransformFunction
        DefaultRootObject: index.html
        Enabled: True
        PriceClass: PriceClass_100
        Origins:
          - Id: momento
            DomainName: api.cache.cell-us-east-1-1.prod.a.momentohq.com
            OriginPath: /cache/bis
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: Authorization
                HeaderValue: !Ref MomentoApiKey
        ViewerCertificate:
          AcmCertificateArn: !Ref CacheSubdomainCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - cache.helton.farm

  TransformFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true
      FunctionCode: |
        async function handler(event) {
          const request = event.request;
          const pieces = request.uri.split('/');
          const key = pieces[pieces.length - 1];

          request.querystring = `key=${encodeURIComponent(key)}`;

          return request;
        }
      FunctionConfig:
        Runtime: cloudfront-js-2.0
        Comment: Function to return redirects
      Name: transform-function

  CacheSubdomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: cache.helton.farm
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: cache.helton.farm
          HostedZoneId: !Ref HostedZoneId

  CacheRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: cache.helton.farm
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt MomentoCacheDistribution.DomainName

Outputs:
  ApiBaseUrl:
    Description: API Gateway endpoint for the community API
    Value: !Sub 'https://${EmojiApi}.execute-api.${AWS::Region}.amazonaws.com/v1'
